applications:
  -
    name: madeinfranz
    domain: madeinfranz.fr
    image: rg.fr-par.scw.cloud/rwsapps/madeinfranz
    environment: madeinfranz
environments:
  -
    name: madeinfranz
    filename: madeinfranz.env