FROM golang:1.17-alpine

RUN apk update && apk --no-cache add supervisor curl


RUN mkdir -p /go/src/github.com/wormable/nest

ADD . /go/src/github.com/wormable/nest

WORKDIR /go/src/github.com/wormable/nest

RUN go install

EXPOSE 80

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]