name: hezi
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hez makes orchestrating containers easy.
description: |
  A simple tool to orchestrate containers and manage the environement around it.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  test-hez:
    plugin: go
    go-importpath: github.com/redwebcreation/hez
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  hez:
    command: hez
